### ISSUE TITLE
[Bug] import_coloris.default.init is not a function

### ISSUE THREAD

**Issue by jjf21** [melloware/coloris-npm#59]
I have same kind of errors as https://github.com/melloware/coloris-npm/issues/13

Just by adding

```js
import "@melloware/coloris/dist/coloris.css";
import Coloris from "@melloware/coloris";
Coloris.init();
Coloris({el: "#coloris"});
``` 

I have the error:
```
Uncaught TypeError: import_coloris.default.init is not a function
```

Using CDN is working properly, am I missing something ?

**Comment by melloware** [comment]
Are you using the latest version `0.10.3` ?

**Comment by jjf21** [comment]
Yes
```
"@melloware/coloris": "^0.10.3"
```

**Comment by melloware** [comment]
@blutorange this cropped up again but all of our tests are passing where you basically check this.

**Comment by jjf21** [comment]
Is there any manual configuration I can try to help find out the problem ?

**Comment by blutorange** [comment]
The test works because [of this entry](https://github.com/melloware/coloris-npm/blob/main/test-npm/webpack-ts/tsconfig.json#L3) in the `tsconfig.json`

```javascript
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
  }
}
```

The [UMD wrapper has](https://github.com/melloware/coloris-npm/blob/main/umd-wrapper.js#L29)

>     module.exports.Coloris = factory();

where `factory()` is the Coloris function/object. So with plain commonJS , that would be `const {Coloris} = require("@melloware/coloris")`. 

Can't quite remember why we didn't make that `module.exports = factory();`, but I suppose it was because otherwise it'd be incompatible with some parts of the ecosystem (TS, other module systems etc.)

**Comment by blutorange** [comment]
I think it may have been (at least partially) due to AMD / requirejs support. At any rate, changing that right now would probably result in issues for people already using this lib. So for now, I'd say we should just update the docs and re-evaluate whether we want to change the module wrapper with the next major release of Coloris.

**Comment by melloware** [comment]
I am ok with breaking this wrapper to get it right. We only have about 80 downloads a week and increasing each month. Better to fix it for good sooner than later?

**Comment by blutorange** [comment]
Hmm ok, but I need to think about whether that is right or not. I might have some time during the next few days. I guess we should start by adding more a few tests with webpack and other bundlers, with / without TS.

**Comment by melloware** [comment]
Ok no worries.  You are the expert!

**Comment by jjf21** [comment]
Hi, thanks for your work but it is still not working.

Even with:
```js
import "@melloware/coloris/dist/coloris.css";
import { coloris, init } from "@melloware/coloris";
init();
coloris({el: "#coloris"});
```

**Comment by blutorange** [comment]
@jjf21 Could you share a simple project that illustrates the issue? Might be specific to whatever bundler etc. you are using. Also, did you test against the current version in this github repo since I believe there was no release yet with the change?

**Comment by blutorange** [comment]
I uploaded version [0.10.4-rc1](https://www.npmjs.com/package/@melloware/coloris/v/0.10.4-rc1) to npm if you want to try.

**Comment by jjf21** [comment]
In fact I tried it with 
```
yarn add ssh://git@github.com:melloware/coloris-npm.git#main
```

using `0.10.4-rc1` works perfectly !

Thanks for your help !
