### ISSUE TITLE
Builds Failing

### ISSUE THREAD

**Issue by melloware** [melloware/coloris-npm#78]
@blutorange Do you mind looking into why the builds are failing?  It doesn't look like any code was changed but they seem to be failing

**Comment by blutorange** [comment]
Looks very interesting, perhaps a new version of the bundler that maks it fail? Let me see...

**Comment by blutorange** [comment]
Seems there was a change in node's experimental custom ESM loader implementation, had to update yarn. Build should be working now again

**Comment by melloware** [comment]
You rock!

**Comment by melloware** [comment]
@blutorange I just pulled in the latest Coloris changes and the build is failing?  What is weird is it converted what looks like ES2015 code using `const` back to `var`  but looking at his main source repo its always been `var`.  Did we change something in the source?

**Comment by blutorange** [comment]
Do you mean this, which was once `window.Coloris`? We had to change that so that we only expose it globally when not running in a module environment. Other than that, it seems that many `const` were changed to `var` at some point in the original repo.

https://github.com/mdbassit/Coloris/blob/v0.1.0/src/coloris.js

![image](https://user-images.githubusercontent.com/2456413/233354201-a5cfcd8d-e35b-46ae-98fe-c52ecf4ffd7c.png)

**Comment by melloware** [comment]
No it was my bad i copied his coloris.js from `dist` and not from his `source`.

**Comment by melloware** [comment]
False alarm
